version: "3.8"

services:
  # .pinkyring=MONGO
  mongo:
    container_name: mongo
    image: mongo:7.0.5
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - mongoConfig:/data/configdb

  # default auth credentials?: admin:pass
  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:mongo@mongo:27017/
    ports:
      - 8081:8081
    volumes:
      - mongo-express:/data/db
    depends_on:
      mongo:
        condition: service_started
  # .pinkyring=MONGO.end

# find which volumes need to be created:
# docker image inspect {imageid or name:tag} --format {{.Config.Volumes}}
volumes:
  # .pinkyring=MONGO
  mongo:
  mongoConfig:
  mongo-express:
  # .pinkyring=MONGO.end
